apiVersion: v1
kind: Service
metadata:
  name: mcp-app
  labels:
    app: mcp-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: "mcp-app"
  selector:
    app: mcp-app