FROM python:3.7-alpine3.11
MAINTAINER "Devnetops Team"
RUN apk add --no-cache --virtual .build-deps libressl-dev libffi-dev gcc musl-dev
COPY OnboardManagement/Repo/Repomgmt /RepoMgmt
WORKDIR /RepoMgmt
RUN pip install -r requirements.txt
CMD ["uwsgi", "--ini", "uwsgi.ini"]
