apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt
  labels:
    app: usermgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt
  template:
    metadata:
      labels:
        app: usermgmt
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: usermgmt
        image: devopstudio.azurecr.io/devnops:latest
        ports:
        - containerPort: 8080
