FROM python:3.8-alpine3.11
MAINTAINER "Devnetops Team"
RUN apk add --no-cache --virtual .build-deps openssl-dev libffi-dev gcc musl-dev
COPY SSE/tmp/sse /sse
WORKDIR /sse
RUN mkdir tmp
RUN pip install wheel && pip install -r requirements.txt
CMD ["uwsgi", "--ini", "uwsgi.ini"]