---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse
  labels:
    app: sse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse
  template:
    metadata:
      labels:
        app: sse
    spec:
      imagePullSecrets:
      - name: devnetops
      containers:
      - name: sse
        image: devnetops.azurecr.io/devnetops-sse:t1
        imagePullPolicy: Always
        env:
        - name: redis_url
          value: redis-ls.ethan.svc.cluster.local:6378
#        resources:
#          request:
#            memory: "2Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sse
  labels:
    app: sse
spec:
  selector:
    app: sse
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---

