---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: demo
    labels:
      app: demo
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: demo
    template:
      metadata:
        labels:
          app: demo
      spec:
        imagePullSecrets:
        - name: devnetops
        containers:
        - name: demo
          image: devnetops.azurecr.io/demo:v1
          imagePullPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    name: demo
  spec:
    selector:
      app: demo
    ports:
    - ports:
      port: 8080
      targetPort: 8080
    type: LoadBalancer
          
