---
apiVersion: apps/v1
kind: deployment-testversion
metadata:
  name: deployment-testversion
  labels:
    app: deployment-testversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-testversion
  template:
    metadata:
      labels:
        app: deployment-testversion
    spec:
      imagePullSecrets:
      - name: devnetops
      containers:
      - name: deployment-testversion
        image: devnetops.azurecr.io/devnetops-deployment-testversion:s2
        imagePullPolicy: Always
        env:
        - name: jenkins_url
          value: http://jenkins-master.devnetops.svc.cluster.local:8080/jenkins
        - name: jenkins_username
          value: admin
        - name: jenkins_password
          value: 11bc91ecc7bc9d99bff458b908861586f5
        - name: jenkins_token
          value: 11d2cc12486764cb4e2862d2388b70a826
        - name: jenkins_cft_deploy_job
          value: deployment-testversion/pipelines/cft_deploy
        - name: jenkins_cft_delete_job
          value: deployment-testversion/pipelines/cft_delete
        - name: onboarding_url
          value: http://onboardmgmt.devnetops.svc.cluster.local:8080
        - name: usermgmtUrl
          value: http://usermgmt.devnetops.svc.cluster.local:8080
        - name: mongohost
          value: mongodb://admin:password@mongo.devnetops.svc.cluster.local/devnetops37?authSource=admin
        - name: status_url
          value: http://deployment-testversion.devnetops.svc.cluster.local:8080
        - name: secretkey
          value: 200Gw5vUnsTZBmmRTLzuBiCwrr67Q88xDP-GxwH9CfWuqlWx3ZwNh85LdiatBLiqNX0
        - name: vault_url
          value: http://vault1.devnetops.svc.cluster.local:80
        - name: vault_token
          value: devnetops
        - name: redis_url
          value: redis-ls.devnetops.svc.cluster.local:6378
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-testversion
  labels:
    app: deployment-testversion
spec:
  selector:
    app: deployment-testversion
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: deployment-testversion
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/eventsource: "true"
spec:
  rules:
  - host: dno-dev.acndevopsengineering.com
    http:
      paths:
      - path: /deploy-testversion(/|$)(.*)
        backend:
          serviceName: deployment-testversion
          servicePort: 8080
