apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      imagePullSecrets:
      - name: devnetops
      containers:
      - name: deployment
        image: devnetops.azurecr.io/devnetops-deployment:S1
        imagePullPolicy: Always
        env:
        - name: jenkins_url
          value: http://jenkins-blueocean.ethan.svc.cluster.local:8081/jenkinscore
        - name: jenkins_username
          value: ethanadmin
        - name: jenkins_password
          value: sUh7s0wJk2XMLV2D91
        - name: jenkins_token
          value: 11d2cc12486764cb4e2862d2388b70a826
        - name: jenkins_cft_deploy_job
          value: Dev_Workspace/devnetops/cft_deploy
        - name: jenkins_cft_delete_job
          value: Dev_Workspace/devnetops/cft_delete
        - name: onboarding_url
          value: http://onboard-test.ethan.svc.cluster.local:80
        - name: usermgmtUrl
          value: http://accessmgmt.ethan.svc.cluster.local:80
        - name: mongohost
          value:  mongodb://admin:password@mongo-devnetops.ethan.svc.cluster.local/devnetops?authSource=admin
        - name: status_url
          value: http://deployment.ethan.svc.cluster.local:80
        - name: vault_url
          value: http://vault1.ethan.svc.cluster.local:80
        - name: vault_token
          value: devnetops
        - name: redis_url
          value: redis-ls.ethan.svc.cluster.local:6378
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  selector:
    app: deployment
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080

