apiVersion: v1
kind: List
items:
 
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: weave-scope
      {{- with .Values.serviceAccount.annotations }}
      annotations:
         {{- toYaml . | nindent 8 }}
      {{- end }}  
      labels:
        name: weave-scope
      namespace: {{ .Values.namespace.name }}
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRole
    metadata:
      name: weave-scope
      {{- with .Values.clusterRole.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      labels:
        name: weave-scope
    {{- with .Values.clusterRole.rules }}
    rules:
       {{- toYaml . | nindent 8 }}
    {{- end }}  
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata: 
      name: weave-scope
      {{- with .Values.clusterRolebinding.annotations }}
      annotations:
         {{- toYaml . | nindent 8 }}
      {{- end }}   
      labels:
        name: weave-scope
    roleRef:
      kind: ClusterRole
      name: weave-scope
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: weave-scope
        namespace: {{ .Values.namespace.name }}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: weave-scope-app
      {{- with .Values.deployment.annotations }}
      annotations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      namespace: {{ .Values.namespace.name }}
    spec:
      replicas: {{ .Values.deployment.replicaCount }}
      selector:
        matchLabels:
          app: weave-scope
      revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
      template:
        metadata:          
          labels:
            name: weave-scope-app
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: app
          
        spec:
          containers:
            - name: app
              {{- if .Values.arguments.enabled }}
              args:
                {{ .Values.arguments.args }}
              {{- end }}  
              {{- if .Values.command.enabled }}
              command:
                {{ .Values.command.cmd }}
              {{- end }}   
              env: []
              image: '{{ .Values.image.registry }}'
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.Ports }}
              ports:
                  {{- toYaml . | nindent 14 }}
              {{- end }}
                  
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: weave-scope-agent
      {{- with .Values.daemonSet.annotations }}
      annotations:
         {{- toYaml . | nindent 8 }}
      {{- end }}
      
      labels:
        name: weave-scope-agent
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: agen
      namespace: {{ .Values.namespace.name }}
    spec:
      minReadySeconds: {{ .Values.daemonSet.minReadySeconds }}
      selector:
        matchLabels:
          app: weave-scope
      template:
        metadata:
          
          labels:
            name: weave-scope-agent
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: agent
        spec:
          containers:
            - name: scope-agent
              {{- if .Values.arguments.enabled }}
              args: 
                 {{ .Values.arguments.args1 }}
              {{- end }} 
              {{- if .Values.command.enabled }}
              command: 
                {{ .Values.command.cmd }}
              {{- end }} 
              env:
                - name: KUBERNETES_NODENAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
              image: '{{ .Values.image.registry }}'
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              securityContext:
                privileged: true
              {{- if .Values.customVolumeMounts.enabled }}  
              volumeMounts:
                 {{- toYaml .Values.customVolumeMounts.volumeMountFields | nindent 20 }}
              {{- end }}   
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          hostPID: true
          serviceAccountName: weave-scope
          tolerations:
            - effect: NoSchedule
              operator: Exists
          {{- if .Values.customVolumes.enabled }}    
          volumes:
             {{- toYaml .Values.customVolumes.customVolumeClaimNames | nindent 12 }}
          {{- end }} 
      updateStrategy:
        type: RollingUpdate
