apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  {{- with .Values.service.annotations }}
  annotations:
     {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    name: weave-scope-app
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: app
  namespace: {{ .Values.namespace.name }}
spec:
  {{- with .Values.servicePorts }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    name: weave-scope-app
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: app

