FROM python:3.7-alpine
MAINTAINER "Devnetops Team"
RUN apk add --no-cache --virtual .build-deps openssl-dev libffi-dev gcc musl-dev
COPY OnboardManagement/Onboarding /Onboarding
WORKDIR /Onboarding
RUN mkdir tmp
RUN pip install wheel & pip install -r requirements.txt
RUN apk add clamav && freshclam
CMD ["uwsgi", "--ini", "uwsgi.ini"]
