FROM python:3.8-alpine3.11
MAINTAINER "Devnetops Team"
RUN apk add --no-cache --virtual .build-deps openssl-dev libffi-dev gcc musl-dev
COPY OnboardManagement/tmp/Onboarding /Onboarding
WORKDIR /Onboarding
RUN mkdir tmp
RUN pip install wheel && pip install -r requirements.txt
RUN apk add clamav && freshclam
RUN cd /var/lib/clamav/ && rm bytecode.cvd && rm daily.cvd
CMD ["uwsgi", "--ini", "uwsgi.ini"]
