FROM python:3.7-alpine3.11
MAINTAINER "Devnetops Team"
RUN apk add --no-cache --virtual .build-deps libressl-dev libffi-dev gcc musl-dev
#COPY UserManagement/tmp/UserMgmt /UserMgmt
COPY UserManagement/UserMgmt /UserMgmt
WORKDIR /UserMgmt
RUN pip install -r requirements.txt
CMD ["uwsgi", "--ini", "uwsgi.ini"]
