def label = "Devnetops-${UUID.randomUUID().toString()}"
def serviceaccount = "jenkins-admin"
podTemplate(label: label, serviceAccount: serviceaccount,
           containers: [containerTemplate(name: 'python3', image: 'python:3.8-alpine', ttyEnabled: true, command: 'cat'),
           containerTemplate(name: 'kubectl', image: 'nexgtech/kubectl:1.15', ttyEnabled: true, command: 'cat'),
		   containerTemplate(name: 'curl', image: 'devnetops.azurecr.io/curl', ttyEnabled: true, alwaysPullImage: true, command: 'cat'),
           containerTemplate(name: 'tox', image: 'devnetops.azurecr.io/devnetops-tox-updated', ttyEnabled: true, command: 'cat'),
		   	containerTemplate(name: 'node', image: 'node:14-alpine', ttyEnabled: true, command: 'cat'),
		   containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, alwaysPullImage: true, command: 'cat', ,resourceRequestCpu: '100m',resourceLimitCpu: '4000m',resourceRequestMemory: '100Mi',resourceLimitMemory: '6000Mi'),
           containerTemplate(name: 'docker', image: 'docker:18.09.9', ttyEnabled: true, command: 'cat')],
				volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')],
           		imagePullSecrets: ['devnetops'])

{
    node(label)
    {
		def Commit_Id
        def DockerReg_Url='devnetops.azurecr.io'
		def DockerReg_Credentials='ACR'
        def Docker_Image = 'devnetops-onboard'
        def Image_Tag = 't1'
        def K8s_Deployment = 'devnetops-onboard'
		def SONAR_HOST_URL='https://a71ea3e9d163d47c9a000b392eb54bc3-1901858758.us-west-2.elb.amazonaws.com/sonar/'
		def SONAR_SCANNER='org.sonarsource.scanner.maven'
        def SONAR_PLUGIN='sonar-maven-plugin:3.2'
		 		
		
		try{
       stage('Git Checkout'){
            git branch: Git_Branch,
            url: Git_Url,
            credentialsId: Git_Credential
         
			this.Commit_Id = sh(returnStdout: true, script: 'git rev-parse --short=40 HEAD').trim()
			this.bitbucketStatusNotify('INPROGRESS')
        }
		 
		 
		stage ('UI Code Build'){
            container('node'){
              sh '''#!/bin/sh
			  apk update
			  apk upgrade
			  ls -lrt
			  cd UserInterface/
			  ls -lrt
			  npm -v
			  apk add --no-cache build-base
			  ls -rlt
			  npm install -g create-react-app	
			  npm install
			  ls -rlt
			  npm run build
			  
              '''}
         }
		 
			currentBuild.result = 'SUCCESS'
			echo "RESULT: ${currentBuild.result}"
			echo "Finished: ${currentBuild.result}"
	
          }
			 
			 catch (Exception err) {
        currentBuild.result = 'FAILURE'
        echo "RESULT: ${currentBuild.result}"
        echo "Finished: ${currentBuild.result}"
               }
		finally {
            // Success or failure, always send notifications to bitbucket           
            this.bitbucketStatusNotify(currentBuild.result)
        }
			 
			 
			 
         }
        
		
		}
		 
		
def bitbucketStatusNotify(String state) {
 
    if('SUCCESS' == state || 'FAILED' == state) {
    // Set result of currentBuild !Important!
        currentBuild.result = state
    }
 
   // notifyBitbucket commitSha1: this.Commit_Id, considerUnstableAsSuccess: true, credentialsId: Git_Credential, disableInprogressNotification: false, ignoreUnverifiedSSLPeer: true, includeBuildNumberInKey: false, prependParentProjectKey: false, projectKey: '', stashServerBaseUrl: 'https://innersource.accenture.com/'
}